# -*- coding: utf-8 -*-
"""backend

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JI8fmn1z9FnBhq44adM3PaQ_8rXcx6uY
"""

from bs4 import BeautifulSoup as soup
import requests
import re

#Pass in array of keywords as search queries and number of pdfs to scrape
def get_pdfs(queries):
        queries = queries.split(", ")
        url = "https://www.google.com/search?q="
        for q in queries: 
          url += q + "+"
        url += "filetype%3Apdf"

        with requests.Session() as c:
          page_html = c.get(url)
          page_soup = soup(page_html.text, "html.parser")
          containers = page_soup.find_all('div')
          items = []
          for j in containers:
            if "https" in str(j) and "pdf" in str(j):
              if "google" not in str(j):
                temp = str(str(re.search("(?P<url>https?://[^\s]+)", str(j)).group("url")).split('.pdf')[0]) + ".pdf"
                items.append(temp)
          items = list(set(items))
          urls = []
          for i in items:
            if "200" in str(requests.get(i)):
              if "purdue" not in i:
                urls.append(i)
          return get_page(urls)

def get_page(urls):
  extra = ""
  for i, x in enumerate(urls):
    r = requests.get(x).headers
    try:
      if r['X-Frame-Options'] == "SAMEORIGIN":
        extra += "<br><a href=\"" + x + "\">" + "Practice " + str((i+1)) + " (Embed unavailable)" + "</a><br>"
      else:
        extra += "<br><a href=\"" + x + "\">" + "Practice " + str((i+1)) + "</a><br>" + "<br><iframe src=\"" + x + "\" width=\"80%\" height=\"700px\"></iframe><br>"
    except:
        extra += "<br><a href=\"" + x + "\">" + "Practice " + str((i+1)) + "</a><br>" + "<br><iframe src=\"" + x + "\" width=\"80%\" height=\"700px\"></iframe><br>"

  output = """
  <!DOCTYPE html>
  <html>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
  <!- we used a w3schools stylesheet ->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway">
  <style>
      body,
      h1 {
          font-family: "Raleway", sans-serif
      }
      
      body,
      html {
          height: 100%
      }
      
      .bgimg {
          background-image: url("https://wallpapercave.com/wp/wp3006038.png");
          min-height: 100%;
          background-position: center;
          background-size: cover;
      }
  </style>

  <body>

      <div class="bgimg w3-display-container w3-animate-opacity w3-text-white">
          <div class="w3-display-topleft w3-padding-large w3-xlarge">
              <h3 style="color: rgb(255, 255, 255);">Study Helper</h3>
          </div>
          <br>
          <br>
          <div class="w3-display-center">
              <h2 class="w3-jumbo w3-animate-top" style="color: rgb(253, 253, 253); text-align: center;">Here's what we found</h1>
              <hr class="w3-border-white" style="margin:auto;width:40%;color: black;">
              <p class="w3-large w3-center" style="color: rgb(252, 252, 252);">Some previews may be blocked, but you can still access them with the links.</p>
          </div>
          <div style="margin: auto; align-items: center; justify-content: center; text-align: center;">
              """ + extra + """
          </div>
      </div>

  </body>

  </html>"""
  return output


from flask import Flask, render_template
from flask import request

app = Flask(__name__)

@app.route("/")
def home():
    return render_template("studyhelp2.html")

@app.route('/', methods=['POST'])
def my_form_post():
    text = request.form['text']
    print(text)
    return get_pdfs(text)

app.run(debug=True)

